#!/usr/bin/env python3
"""Rewrite the items cross-validation rejected, with the reason fed back.

    regen_failed.py 2_eval/arm_b.validated.jsonl 1_parsed/blocks.jsonl \
        -o 2_eval/arm_b.regen.jsonl --model glm-5.2

A blind retry reproduces the same mistake -- the generator did not know it was
wrong the first time and still does not. Showing it the checker's specific
complaint ("the gold is a bare fragment whose operative verb is in the parent
stem", "MCR 2.511(F)(2) states the identical rule and the query never says
which court") turns a coin flip into a repair.

The item is regenerated by its ORIGINAL family, deliberately. Handing it to the
other model would confound the arm comparison this whole design exists to make.
"""
from __future__ import annotations

import argparse
import collections
import json
import os
import pathlib
import re
import sys
import threading
import time
import urllib.request
from concurrent.futures import ThreadPoolExecutor

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from eval_prompts import TYPE_BRIEF, SYSTEM             # noqa: E402

KEY_PATH = pathlib.Path(os.path.expanduser("~/.config/ollama/cloud.key"))
URL = "https://ollama.com/api/generate"
LOCK = threading.Lock()
STATS = collections.Counter()
FENCE = re.compile(r"^\s*```(?:json)?\s*|\s*```\s*$", re.M)


def parse_loose(txt):
    body = FENCE.sub("", txt).strip()
    if not body.startswith("{"):
        i, j = body.find("{"), body.rfind("}")
        if i == -1 or j <= i:
            raise ValueError(f"no JSON in {txt[:120]!r}")
        body = body[i:j + 1]
    d = json.loads(body)
    if "query" not in d:
        for a in ("question", "q", "text"):
            if a in d:
                d["query"] = d.pop(a)
                break
    if not d.get("query"):
        raise ValueError("no query")
    d.setdefault("reasoning", "")
    d.setdefault("confidence", "")
    d.setdefault("also_answered_by", [])
    if isinstance(d["also_answered_by"], str):
        d["also_answered_by"] = [d["also_answered_by"]]
    return d


def build(rec, text, siblings):
    v = rec.get("validation", {})
    faults = []
    if v.get("answerable") is False:
        faults.append("The provision does NOT answer your question. You asked "
                      "about something this provision does not settle.")
    if v.get("reveals_answer"):
        faults.append("Your question reused the provision's own distinctive "
                      "wording, so it could be found by string matching.")
    if v.get("realistic") is False:
        faults.append("The phrasing is stilted or reverse-engineered from the "
                      "text rather than how a practitioner would ask.")
    if v.get("better_answer_exists"):
        faults.append("Another provision answers it as well or better: "
                      + ", ".join(v["better_answer_exists"][:4])
                      + ". Narrow the question so ONLY this provision answers "
                        "it -- name the court, the procedural track, or the "
                        "posture that distinguishes it.")
    if rec.get("echo", 0) >= 0.55:
        faults.append(f"Lexical overlap with the provision was "
                      f"{rec['echo']:.0%}, far too high.")
    note = v.get("note") or ""

    sib = "\n".join(f"  {s}" for s in siblings[:25]) or "  (none)"
    return f"""{SYSTEM}

A question you wrote for this benchmark FAILED independent review. Rewrite it.

THE PROVISION
  citation: {rec['citation']}
  text:
{text}

OTHER PROVISIONS UNDER THE SAME RULE
{sib}

YOUR PREVIOUS QUESTION (rejected)
  {rec['query']}

WHY IT FAILED
{chr(10).join('  - ' + f for f in faults) or '  - ' + (note or 'unspecified')}
{('  reviewer note: ' + note) if note else ''}

WRITE A NEW QUESTION of type "{rec['query_type']}"
{TYPE_BRIEF.get(rec['query_type'], '')}

It must fix the fault above AND still satisfy every original requirement:
  - answerable from THIS provision alone
  - no citation or rule number in the question text
  - do not reuse the provision's distinctive wording
  - specific enough to have one best answer
  - sounds like a practitioner with a file open

RETURN EXACTLY THIS JSON SHAPE:

{{
  "query": "<the new question>",
  "reasoning": "<one sentence: why {rec['citation']} answers it and the twin does not>",
  "also_answered_by": [],
  "confidence": "high" | "medium" | "low"
}}

Output the JSON object and nothing else -- no prose, no code fence."""


def call(model, prompt, key, attempts=4, timeout=240):
    body = {"model": model, "prompt": prompt, "stream": False,
            "think": False, "options": {"temperature": 0.9}}
    last = None
    for i in range(attempts):
        try:
            req = urllib.request.Request(
                URL, json.dumps(body).encode(),
                {"Content-Type": "application/json",
                 "Authorization": f"Bearer {key}"})
            with urllib.request.urlopen(req, timeout=timeout) as r:
                d = json.load(r)
            out = parse_loose((d.get("response") or "").strip())
            with LOCK:
                STATS["ok"] += 1
            return out
        except Exception as exc:                        # noqa: BLE001
            last = exc
            with LOCK:
                STATS["retry"] += 1
            time.sleep(min(2 ** i, 15))
    with LOCK:
        STATS["fail"] += 1
    raise RuntimeError(f"regeneration failed: {last}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("validated")
    ap.add_argument("blocks")
    ap.add_argument("-o", "--out", required=True)
    ap.add_argument("--model", default="glm-5.2")
    ap.add_argument("--concurrency", type=int, default=8)
    ap.add_argument("--limit", type=int)
    args = ap.parse_args()

    key = KEY_PATH.read_text().strip()
    recs = [json.loads(l) for l in open(args.validated) if l.strip()]
    blocks = [json.loads(l) for l in open(args.blocks) if l.strip()]
    parts = collections.defaultdict(list)
    for b in blocks:
        if b.get("citation") and b["kind"] == "body":
            parts[b["citation"]].append(b["text"])
    text_of = {c: "\n\n".join(v) for c, v in parts.items()}
    sibs = collections.defaultdict(list)
    for c in text_of:
        m = re.match(r"MCR (\d+\.\d+[A-Za-z]?)", c)
        if m:
            sibs[m.group(1)].append(c)

    out_path = pathlib.Path(args.out)
    done = set()
    if out_path.exists():
        for l in open(out_path):
            if l.strip():
                done.add(json.loads(l)["query_id"])
    todo = [r for r in recs
            if r["status"] in ("rejected", "needs_revision")
            and r["query_id"] not in done]
    if args.limit:
        todo = todo[:args.limit]
    print(f"regenerating {len(todo)} failed items with {args.model}")

    fh = open(out_path, "a")

    def work(r):
        text = text_of.get(r["citation"])
        if not text:
            return
        try:
            new = call(args.model,
                       build(r, text, sibs.get(r["rule"], [])), key)
        except Exception as exc:                        # noqa: BLE001
            print(f"  FAIL {r['query_id']}: {exc}", flush=True)
            return
        rec = dict(r)
        rec["query_previous"] = r["query"]
        rec["query"] = new["query"].strip()
        rec["generator_reasoning"] = new.get("reasoning", "")
        rec["generator_confidence"] = new.get("confidence", "")
        rec["regenerated"] = True
        rec["regen_reason"] = (r.get("validation", {}) or {}).get("note", "")
        rec["status"] = "draft"
        rec.pop("validation", None)
        rec.pop("echo", None)
        with LOCK:
            fh.write(json.dumps(rec, ensure_ascii=False) + "\n")
            fh.flush()

    t0 = time.time()
    with ThreadPoolExecutor(max_workers=args.concurrency) as ex:
        list(ex.map(work, todo))
    fh.close()
    print(f"\ndone in {(time.time()-t0)/60:.1f} min · {dict(STATS)}")


if __name__ == "__main__":
    sys.exit(main())
