#!/usr/bin/env python3
"""Search interface for the Michigan Court Rules.

    python3 pipeline/serve.py --port 8788   ->  http://127.0.0.1:8788

Server-rendered HTML from the stdlib, following carolina-policy-search: no
build step, no framework, nothing to install beyond the engine itself. The page
is meant to be shown to judges and clerks, so it says where every sentence came
from and never hides a refusal.
"""
from __future__ import annotations

import argparse
import html
import pathlib
import sys
import time
import urllib.parse
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from mcr_search import Engine, GEN_MODEL            # noqa: E402

ENGINE: Engine | None = None

EXAMPLES = [
    "How long does a defendant served in Michigan have to answer a complaint?",
    "MCR 2.116(C)(10)",
    "Can I serve process on someone confined in a psychiatric facility?",
    "When must a court appoint a guardian ad litem for a minor?",
    "What must a motion for summary disposition specify?",
    "When can a PPO action be dismissed?",
]

CSS = """
:root{color-scheme:light dark;--bg:#fff;--fg:#16181d;--mut:#6a7280;
--line:#e2e5ea;--card:#fafbfc;--accent:#1b6ac9;--router:#0a7;--warn:#c80}
@media(prefers-color-scheme:dark){:root{--bg:#111317;--fg:#e8eaed;--mut:#9aa2ad;
--line:#2a2e35;--card:#181b20;--accent:#6aa9f0}}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);
font:15.5px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif}
header{border-bottom:1px solid var(--line);padding:18px 20px}
.wrap{max-width:900px;margin:0 auto}
h1{font-size:19px;margin:0 0 2px}
h1 span{color:var(--mut);font-weight:400}
.sub{color:var(--mut);font-size:13px}
form{display:flex;gap:8px;margin:16px 0 6px;flex-wrap:wrap}
input[type=text]{flex:1;min-width:260px;padding:11px 13px;font:inherit;
border:1px solid var(--line);border-radius:9px;background:var(--card);
color:var(--fg)}
button,select{padding:11px 15px;font:inherit;border:1px solid var(--line);
border-radius:9px;background:var(--card);color:var(--fg);cursor:pointer}
button.go{background:var(--accent);color:#fff;border-color:transparent}
.opts{display:flex;gap:14px;align-items:center;color:var(--mut);font-size:13px;
flex-wrap:wrap;margin-bottom:4px}
main{max-width:900px;margin:0 auto;padding:20px}
.ex a{color:var(--accent);text-decoration:none;font-size:13.5px;
border:1px solid var(--line);border-radius:20px;padding:4px 11px;
display:inline-block;margin:0 6px 7px 0}
.answer{border:1px solid var(--line);border-left:3px solid var(--accent);
border-radius:9px;padding:14px 16px;background:var(--card);margin-bottom:22px;
white-space:pre-wrap}
.answer.refused{border-left-color:var(--warn)}
.answer h3{margin:0 0 8px;font-size:13px;color:var(--mut);font-weight:600;
letter-spacing:.04em;text-transform:uppercase}
.hit{border:1px solid var(--line);border-radius:9px;padding:12px 14px;
margin-bottom:11px;background:var(--card)}
.hit .cite{font-weight:650;color:var(--accent)}
.hit .path{color:var(--mut);font-size:12.5px;margin:3px 0 8px}
.hit .body{font-size:14px;white-space:pre-wrap;max-height:230px;overflow:auto}
.badge{display:inline-block;font-size:11.5px;border:1px solid var(--line);
border-radius:20px;padding:1px 8px;color:var(--mut);margin-left:7px}
.badge.router{border-color:var(--router);color:var(--router)}
footer{max-width:900px;margin:0 auto;padding:8px 20px 40px;color:var(--mut);
font-size:12.5px;border-top:1px solid var(--line)}
"""


def page(q, mode, want_answer, body):
    ex = "".join(
        f'<a href="/?q={urllib.parse.quote(e)}&mode={mode}'
        f'{"&answer=1" if want_answer else ""}">{html.escape(e)}</a>'
        for e in EXAMPLES)
    sel = lambda v: " selected" if v == mode else ""
    return f"""<!doctype html><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Michigan Court Rules — search</title><style>{CSS}</style>
<header><div class="wrap">
  <h1>Michigan Court Rules <span>— search</span></h1>
  <div class="sub">874 pages · 625 rules · 11,293 citable provisions · updated
    July 31 2026 · answers generated by {html.escape(GEN_MODEL)}</div>
  <form method="get" action="/">
    <input type="text" name="q" value="{html.escape(q)}"
           placeholder="Ask a question, or paste a citation like MCR 2.116(C)(10)" autofocus>
    <select name="mode">
      <option value="hybrid"{sel('hybrid')}>hybrid</option>
      <option value="dense"{sel('dense')}>dense only</option>
      <option value="bm25"{sel('bm25')}>keyword only</option>
    </select>
    <button class="go" type="submit">Search</button>
  </form>
  <div class="opts">
    <label><input type="checkbox" form="" disabled {'checked' if want_answer else ''}>
      &nbsp;</label>
  </div>
  <div class="ex">{ex}</div>
</div></header>
<main>{body}</main>
<footer>Every answer is drawn only from the passages shown and cites them
inline; when the rules do not answer a question the system says so rather than
guessing. Source: Michigan Court Rules, courts.michigan.gov.</footer>"""


def hit_card(h):
    router = h["how"] == "citation-router"
    return f"""<div class="hit">
  <span class="cite">{html.escape(h['citation'] or h['rule'])}</span>
  <span class="badge{' router' if router else ''}">
    {'exact citation' if router else h['how']}</span>
  <span class="badge">p.{h['pages'][0] + 1 - 18}</span>
  <div class="path">{html.escape(h['heading_path'])}</div>
  <div class="body">{html.escape(h['text'][:1600])}</div>
</div>"""


def render(q, mode, want_answer):
    if not q.strip():
        return "<p style='color:var(--mut)'>Ask a question above, or try an example.</p>"
    t0 = time.time()
    if want_answer:
        r = ENGINE.answer(q, k=6, mode=mode)
        hits, ans = r["hits"], r["answer"]
    else:
        hits, ans = ENGINE.search(q, k=8, mode=mode), None
    dt = time.time() - t0

    out = []
    if ans:
        refused = any(s in ans.lower() for s in
                      ("do not answer", "does not answer", "not answered",
                       "no provision", "cannot be answered"))
        out.append(f"""<div class="answer{' refused' if refused else ''}">
  <h3>{'Not answered by the court rules' if refused else 'Answer'}</h3>
  {html.escape(ans)}</div>""")
    out.append(f"<div class='sub' style='margin-bottom:10px'>"
               f"{len(hits)} passages · {dt:.1f}s</div>")
    out += [hit_card(h) for h in hits]
    return "".join(out)


class Handler(BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"

    def log_message(self, *a):
        pass

    def do_GET(self):
        u = urllib.parse.urlparse(self.path)
        if u.path not in ("/", "/index.html"):
            self.send_response(404)
            self.send_header("Content-Length", "0")
            self.end_headers()
            return
        qs = urllib.parse.parse_qs(u.query)
        q = (qs.get("q") or [""])[0]
        mode = (qs.get("mode") or ["hybrid"])[0]
        want = bool(qs.get("answer")) or bool(q.strip())
        body = page(q, mode, want, render(q, mode, want))
        b = body.encode()
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(b)))
        self.end_headers()
        self.wfile.write(b)


def main():
    global ENGINE
    ap = argparse.ArgumentParser()
    ap.add_argument("--port", type=int, default=8788)
    args = ap.parse_args()
    print("building index...", flush=True)
    ENGINE = Engine(quiet=True)
    _ = ENGINE.vecs
    _ = ENGINE.bm25
    print(f"ready · {len(ENGINE.chunks):,} chunks · "
          f"http://127.0.0.1:{args.port}", flush=True)
    ThreadingHTTPServer(("127.0.0.1", args.port), Handler).serve_forever()


if __name__ == "__main__":
    main()
