#!/usr/bin/env python3
"""Anthropic-style contextual retrieval: a per-chunk blurb, written locally.

    contextualize.py 3_chunks/v_rule512.jsonl -o 3_chunks/context.jsonl

Generated by qwen3.6:27b running on this machine -- no corpus text leaves it,
and the whole corpus is public anyway, so the choice is about reproducibility
rather than privacy: a local weight file can be pinned, a hosted endpoint
cannot.

What the model is given, and why it is the rule rather than the document.
Anthropic's method shows the generator the whole document. Here the whole
document is 874 pages, and the unit that actually disambiguates a provision is
its RULE: the same sentence appears verbatim under four different citations
(115 such groups in this corpus), and what separates them is which rule they
sit in. So the rule is the context window that carries the signal.

The CPS bake-off found this lever raises the FLOOR rather than the ceiling --
mpnet +18 points, Linq +1 (p = 1.0). With a strong embedder fixed here, the
honest expectation is a small effect. It is measured rather than assumed.
"""
from __future__ import annotations

import argparse
import collections
import json
import pathlib
import sys
import threading
import time
import urllib.request
from concurrent.futures import ThreadPoolExecutor

HOST = "http://127.0.0.1:11434/api/generate"
MODEL = "qwen3.6:27b-q4_K_M"
RULE_CAP = 6000
LOCK = threading.Lock()
STATS = collections.Counter()

PROMPT = """<rule>
Michigan Court Rules — Chapter {chapter}{sub}
{rule_title}

{rule_text}
</rule>

Here is one passage taken from the rule above:
<passage>
{chunk}
</passage>

Write ONE sentence of at most 40 words situating this passage within the
Michigan Court Rules, so that a search engine can tell it apart from similar
passages elsewhere. Name the proceeding or posture it governs, the actor it
binds, and the subsection. Do not restate the passage. Do not add anything
that is not in the rule above.

Answer with the sentence only."""


def gen(prompt, timeout=180, attempts=3):
    body = {"model": MODEL, "prompt": prompt, "stream": False, "think": False,
            "options": {"temperature": 0.2, "num_predict": 90}}
    last = None
    for i in range(attempts):
        try:
            req = urllib.request.Request(
                HOST, json.dumps(body).encode(),
                {"Content-Type": "application/json"})
            with urllib.request.urlopen(req, timeout=timeout) as r:
                d = json.load(r)
            t = (d.get("response") or "").strip().strip('"')
            if t:
                with LOCK:
                    STATS["ok"] += 1
                return " ".join(t.split())
            raise ValueError("empty")
        except Exception as exc:                        # noqa: BLE001
            last = exc
            with LOCK:
                STATS["retry"] += 1
            time.sleep(min(2 ** i, 8))
    with LOCK:
        STATS["fail"] += 1
    raise RuntimeError(str(last))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("chunks")
    ap.add_argument("--blocks", default="1_parsed/blocks.jsonl")
    ap.add_argument("-o", "--out", default="3_chunks/context.jsonl")
    ap.add_argument("--workers", type=int, default=4)
    ap.add_argument("--limit", type=int)
    args = ap.parse_args()

    chunks = [json.loads(l) for l in open(args.chunks) if l.strip()]
    blocks = [json.loads(l) for l in open(args.blocks) if l.strip()]
    rule_text = collections.defaultdict(list)
    for b in blocks:
        if b["kind"] == "body" and b.get("rule"):
            rule_text[b["rule"]].append(b["text"])
    full = {r: "\n\n".join(v)[:RULE_CAP] for r, v in rule_text.items()}

    out_path = pathlib.Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    done = set()
    if out_path.exists():
        for l in open(out_path):
            if l.strip():
                done.add(json.loads(l)["chunk_id"])
    todo = [c for c in chunks if c["chunk_id"] not in done]
    if args.limit:
        todo = todo[:args.limit]
    print(f"{MODEL} · {len(todo):,} chunks to contextualise "
          f"({len(done):,} done)", flush=True)

    fh = open(out_path, "a")
    t0 = time.time()

    def work(c):
        try:
            ctx = gen(PROMPT.format(
                chapter=c["chapter"],
                sub=f" > {c['subchapter']}" if c.get("subchapter") else "",
                rule_title=c["rule_title"],
                rule_text=full.get(c["rule"], c["text"]),
                chunk=c["text"][:2400]))
        except Exception as exc:                        # noqa: BLE001
            print(f"  FAIL {c['chunk_id']}: {exc}", flush=True)
            return
        with LOCK:
            fh.write(json.dumps({"chunk_id": c["chunk_id"],
                                 "context": ctx}, ensure_ascii=False) + "\n")
            fh.flush()
            n = STATS["ok"]
            if n and n % 100 == 0:
                el = time.time() - t0
                print(f"  {n:,}/{len(todo):,} · {el/60:.1f} min · "
                      f"{el/n:.1f}s each · eta {(len(todo)-n)*el/n/60:.0f} min",
                      flush=True)

    with ThreadPoolExecutor(max_workers=args.workers) as ex:
        list(ex.map(work, todo))
    fh.close()
    print(f"\ndone in {(time.time()-t0)/60:.1f} min · {dict(STATS)}")


if __name__ == "__main__":
    sys.exit(main())
